### ISSUE TITLE
Feature request : webdav interface

### ISSUE THREAD

**Issue by sclikaflon** [rfjakob/gocryptfs#216]
A cool feature : adding Windows support by exposing cleartext dir through Webdav instead of FUSE.

I don't know if this requires a lot of work (the golang.org/x/net/webdav library looks simple to use, but I don't know gocryptfs enough to determine if it exposes everything webdav needs) but that would make gocryptfs the portable and performant encrypted filesystem that can be used without admin privileges on both systems.

**Comment by rfjakob** [comment]
Oh no, webdav is an endless source of pain - and slow as hell.

For windows, have you looked at the cppcryptfs port?

**Comment by sclikaflon** [comment]
I didn't know about it, but it has the same problem as many others : it requires, at some point, admin privileges (in the particular case of cppcryptfs, they are needed by the dokany driver installation).

**Comment by rfjakob** [comment]
Maybe you can find a way to get your Windows Admin to install the Dokany driver?

For WebDAV, you could take a look at https://github.com/cryptomator/cryptomator , they use WebDAV exclusively.

They are [considering](https://github.com/cryptomator/cryptomator/issues/252) switching to FUSE because of that endless source of pain thing, though.
