### ISSUE TITLE
Any value in mounting only a sub-directory?

### ISSUE THREAD

**Issue by lechner** [rfjakob/gocryptfs#256]
Hi,

I can see a scenario for someone hoping to encrypt data with the same underlying key but wishing to mount only a sub-directory. For example, one could keep both a home directory and data for a local IMAP server (that's only used when logged in) together in one volume. There would be only one key to back up and only one password to change, thus lessening the chance of a lockout.

Presently one would keep both such folders in an encrypted directory one level up, mount that on something like `/private` and then bind mount the components elsewhere (like `/home` and maybe `/mail`). Overall, the idea is similar to btrfs's `subvol` although it only saves a bind mount. At the same time, two `gocryptfs` processed may be faster than one. Does that sound like a useful feature? Thank you!

Best regards,
Felix

**Comment by rfjakob** [comment]
Hi Felix! Not sure if the extra code complexity is worth it. My understanding is that bind mounts work fine and are well-understood by users.

About the speed, it *should* not make a difference if there are two processes or one, as the requests will be processed in parallel in any case due to multithreading. I just did a quick test writing 2 x 100MB in parallel to one or two gocryptfs instances:

One instance, mounted at `b`:
```
dd if=/dev/zero of=b/zero  bs=1M count=100 & \
dd if=/dev/zero of=b/zero2 bs=1M count=100 & \
wait
104857600 bytes (105 MB, 100 MiB) copied, 0.783427 s, 134 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 0.777828 s, 135 MB/s
```

Two instances, mounted at `b` and `d`:
```
dd if=/dev/zero of=b/zero bs=1M count=100 & \
dd if=/dev/zero of=d/zero bs=1M count=100 & \
wait
104857600 bytes (105 MB, 100 MiB) copied, 0.741769 s, 141 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 0.768141 s, 137 MB/s
```

Some thing for reading:

One instance, mounted at `b`:
```
dd of=/dev/null if=b/zero bs=1M count=100 & \
dd of=/dev/null if=b/zero2 bs=1M count=100 & \
wait
104857600 bytes (105 MB, 100 MiB) copied, 0.655664 s, 160 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 0.696379 s, 151 MB/s
```

Two instances, mounted at `b` and `d`:
```
dd of=/dev/null if=b/zero bs=1M count=100 & \
dd of=/dev/null if=d/zero bs=1M count=100 & \
wait
104857600 bytes (105 MB, 100 MiB) copied, 0.692366 s, 151 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 0.702374 s, 149 MB/s
```

The measurements look close enough for me to say it doesn't really matter.

**Comment by lechner** [comment]
Hi, great points on the complexity and the performance data! Issue is closed. Thank you!
