### ISSUE TITLE
two-way sync for RO reverse mount

### ISSUE THREAD

**Issue by brainchild0** [rfjakob/gocryptfs#345]
Please forgive that this issue represents a question rather than an identified need for a modification.  I find no other forum for such discussion, and I have discovered no appropriate answers in the documentation

Following from #279 and #151, my understanding is that cloud synchronization is a design consideration, with the case of multiple clients synchronizing the same encrypted storage being a supported case.  I also understand that one of the purposes of reverse mode is to facilitate encrypted backend storage without encrypting the underlying storage on the client system.

However, I am finding a few obstacles trying to achieve such a configuration in the reverse-mode case.  First, I find that the target of the reverse mount, that is, the encrypted representation, is a read-only file system, meaning that a synchronization client cannot apply modifications from other clients, such that they would produce a change in the unencrypted source location.  Second, I find that many synchronization clients attempt to write metadata representing the synchronization state against the server inside the synchronized directory, which in this case is not only read-only, but encrypted.

Perhaps I have misunderstood, but as I find no other source for such information, perhaps someone could help me understand whether and how the desired configuration is possible.

(Following from previous discussions, I initialized the reverse storage with the `-aessiv` switch.)

**Comment by slackner** [comment]
Using the issue tracker for questions is fine.

Your idea described above, using a reverse mount and syncing the encrypted view back and forth to a cloud storage provider, is unfortunately not (yet) supported. As you already noticed, reverse mode currently only provides an encrypted read-only view of your source directories. Modifying files in the reverse mount is not supported and would require quite a lot of changes, so this will unlikely happen in the near future. The whole synchronization with multiple clients would also be a bit error-prone: If two files differ, how do you know in which direction you have to synchronize to make sure no changes are lost?

Nevertheless, there might be easier ways to achieve your goal. Have you already decided which cloud storage provider you use? If your cloud storage can be mounted somewhere in your file system, you can also use forward mode, for example. You only have to be careful about two things:

* When creating directories while being offline bug #151 could cause trouble (mainly because the synchronization client does not know how to handle differing `gocryptfs.diriv` files created on both machines). Support for deterministic dirIVs in forward mode will fix that.

* In general, cloud synchronization clients can be less clever when merging changes done on multiple machines (since they cannot recognize text/document files due to encryption). This is something that cannot be easily fixed.

If you also prefer to keep an unencrypted version of your data, you could theoretically also run `rsync` locally, to synchronize between your unencrypted version and your gocryptfs forward mount. Please note, however, that this suffers from the same problem as above.

**Comment by slackner** [comment]
I don't think gocryptfs in reverse mode would ever work as well as integrated client-side encryption. Most cloud storage applications will provide their own FUSE (or kernel) filesystem, so you have two directories containing encrypted content, the local one (mounted in reverse mode) and the remote one (the version on your cloud storage). But what is still missing is the synchronization part: How do you detect changes to your local (or remote) files and synchronize them with each other, while always preserving the latest version? What should happen if both the local and remote version have been modified at the same time? This also is a non-trivial task, and cloud storage applications usually do a much better job than just a simple script that is run every couple of minutes.

Even if you don't necessarily need an additional layer of encryption, with current versions of gocryptfs the best option for your specific application would be to use forward mode. The gocryptfs mountpoint could also be mounted automatically, if you do not care about having the passphrase in some local file.

**Comment by brainchild0** [comment]
Yes, I suppose if I am dealing with data that I would be willing to store locally without encryption, then it is equally (in)secure to encrypt with a local, clear copy of the key.  In this case, is it supported and safe that a synchronization client modify the encrypted volume while a view is mounted simultanously (and accessed by applications)?

Also, do I understand correctly that you say that solutions are already available such that a client can synchronize encrypted data without access to the key, and that the same local copy can be later or simultaneously be mounted into a decrypted view?

**Comment by rfjakob** [comment]
> is it supported and safe that a synchronization client modify the encrypted volume while a view is mounted simultanously (and accessed by applications)?

Like Dropbox? Yes!

**Comment by brainchild0** [comment]
How do conflicts get handled, in this case?

**Comment by Nodens-** [comment]
Although I use gocryptfs and cppcryptfs extensively this is one of my use cases that I actually dropped into other kind of encryption due to the fact that there is no deterministic reverse mode and said data have to remain unencrypted locally. I ended up using GoodSync's encryption.
If there was support for deterministic reverse (which would also allow RW reverse), GoodSync and a LOT of other multicloud syncing clients (or even directory syncing clients for cases where the cloud storage is mounted as a drive/directory) can easily handle the intricacies of multipoint syncing. Even locking is supported by GoodSync for example. This is not something that can or should be handled at the encryption layer but at the application layer (software used for syncing).
I do hope that this will get implemented at some point so I can unify my encryption scheme to gocryptfs which is faster and more secure by far.

**Comment by brainchild0** [comment]
It would be helpful to understand how conflicts are handled when an encrypted store is shared by synchronization software.  Normally, such software will write an additional file, with a name automatically generated from the original one.  A user might find a file called `my document (conflict).docx` to represent that changes occurred to both the local and remote copies of `my document.docx` since the last synchronization.  Since the file names on the encrypted store are cryptographic representations of the actual name, and since `<opaquename> (conflict)` does not decrypt to `<original name> (conflict)`, I am wondering what the experience is for users who have configured this arrangement.  

Thank you.

**Comment by rfjakob** [comment]
Well, the user experience is not very good. You'll get something like `9sv5JFmMzhvBE7faKVZZdQ (conflict)`. This does not decrypt, and gocryptfs will log an error and ignore the file. So basically, those "(conflict)" files become invisible.

**Comment by brainchild0** [comment]
If the physical file name ordinarily is a symmetrically encrypted representation of the unencrypted file name, and if no possible encrypted name is a prefix to any other possible name, then it should be possible to insert a rule, such that for for all physical and unencrypted names `<pname>` and `<uname>` that map to each other, then all `<pname><extra_text>` and `<uname><extra_text>` also map to each other, for any extra unencrypted text `<extra_text>`.  Thus, such insertions are seen and can be resolved by the user, without exposing any sensitive data either to a  network client or an attacker who can read the physical store.  The added text is assumed to be a generic string, contained in the distribution of the network client, not regarded as sensitive.  Meanwhile, any explicit renaming of the file within the mounted volume would then become named by a fully encrypted representation of the name provided by the user.

Thus if `foo` is represented as `9sv5JFmMzhvBE7faKVZZdQ`, then `9sv5JFmMzhvBE7faKVZZdQ (conflict)` represents `foo (conflict)`,  Whenever the user might change `foo (conflict)` to `bar (conflict)`, then that entire name, including ` (conflict)` is used to generate a new encrypted name following usual rules, and ` (conflict)` no longer appears in the physical store.

One caveat is file extensions, since most clients will add the postfix to the basename, to preserve the extension, however, even the straightforward behavior proposed above might be extremely helpful.

**Comment by rfjakob** [comment]
Continuing at https://github.com/rfjakob/gocryptfs/issues/393 .
