### ISSUE TITLE
mount smb share

### ISSUE THREAD

**Issue by stephane-21** [rfjakob/gocryptfs#407]
I have an encrypted folder stored on a drive accessible through the smb protocol.
And I want to mount locally a cleared view of that folder.

With Ubuntu 19.04 the folder is accessible here :
smb://192.168.0.22/shared/Backup/

Or here, when mounted with "Thunar file explorer" :
/run/user/1000/gvfs/smb-share:server=192.168.0.22,share=shared/Backup

**This command returns an error :**
gocryptfs /run/user/1000/gvfs/smb-share:server=192.168.0.22,share=shared/Backup /mnt/HDD/Mount/test
fuse.NewServer failed: found ',' in option string "fsname=/run/user/1000/gvfs/smb-share:server=192.168.0.22,share=shared/Backup"

**This command also returns an error :**
gocryptfs smb://192.168.0.22/shared/Backup/ /mnt/HDD/Mount/test
Invalid cipherdir: stat /home/user/Desktop/smb:/192.168.0.22/shared/Backup: no such file or directory

Maybe I am not using gocryptfs in the right way ?
(My main goal is just to do a encrypted backup through the network with grsync)
(I have seen that I could also use the reverse mode, but still the normal mode would be needed in the case I want to access my backup in a read-only way)

gocryptfs -version
gocryptfs 1.4.3; go-fuse 0.0~git20180810.95c6370; 2018-09-14 go1.10.4

**Comment by rfjakob** [comment]
Oh dear, that seems to be because of the comma ","  in the folder name.

As a quick workaround, and also for perfomance reasons, I would recommend to mount the smb share like this:

sudo mkdir /mnt/shared
sudo mount -t cifs //192.168.0.22/shared /mnt/shared

With /mnt/shared, gocryptfs should work fine

**Comment by stephane-21** [comment]
Thank you for the very fast answer,
I will try that.
I was hopping for a solution without intermediate mount, but at least I have that solution which should work.

(PS : I go to Vienna for holidays next week)

**Comment by rfjakob** [comment]
Looks like this problem has been reported as https://github.com/rfjakob/gocryptfs/issues/262 some time earlier, and was fixed in gocryptfs v1.7, released in March 2019. You can download the binary here: https://github.com/rfjakob/gocryptfs/releases

However, it seems that gvfs has problems with multithreaded writes, so `mount -t cifs` might still be the better option.

Hope you have a good time in Vienna :)

**Comment by stephane-21** [comment]
I have installed the latest version :
gocryptfs v1.7-41-gf1b538e; go-fuse v2.0.2-1-ga3bb218; 2019-08-10 go1.10.4 linux/amd64
I can now indeed mount the folder with gocryptfs, but I get gfvs errors when using the "plain" folder.

I was hopping to find a solution into that direction because it doesn't requires the "sudo" command.
It would have been more elegant.
Because in the end, the admin rights should not be needed to mount a folder that the user already has access to.
