### ISSUE TITLE
Provide binaries for all supported platform in release assets

### ISSUE THREAD

**Issue by ylogx** [rfjakob/gocryptfs#414]
Golang can be used to build cross platform binaries. 
The release assets should include not only linux but also mac and windows binaries.

**Comment by rfjakob** [comment]
Unfortunately, I can only test on Linux, so I only feel comfortable to release binaries for Linux. For MacOS, the homebrew people do a good job, and I think they test before they release binaries. For Windows, gocryptfs does not work at all, because Windows does not have FUSE (though https://github.com/billziss-gh/winfsp looks very promising), and does not have a lot of the kernel features gocryptfs relies on.
