### ISSUE TITLE
base32 encoded filenames

### ISSUE THREAD

**Issue by bogdan2412** [rfjakob/gocryptfs#466]
Right now it seems like the only option for filename encoding involves using base64, however this is not ideal for use with certain cloud providers like Dropbox which implement a case insensitive file system.  Adding something like base32 filename encoding would help with this problem.

**Comment by rfjakob** [comment]
I'm not sure if this really is a problem - is it? As far as I know, everything is at least **case-preserving**, which should be good enough for gocryptfs.

**Comment by bogdan2412** [comment]
I guess I've followed the example of rclone and encfs on this without thinking about it deeply.  I'm not sure how to model the probability of conflict where two different files get mapped to the different encrypted paths that are equal when ignoring case, do you have any insight there?

It also seems a bit scary to rely on case-preserving behaviour to me, I'm probably being paranoid around cloud providers loosening their guarantees about it or around hitting bugs around it.  For example, I think the Dropbox API gives you lower case path components for everything apart from the last component, so they likely store things indexed by their lower case path and then have to maintain additional metadata per object with the correct case, which is maybe a source for future mistakes, it seems more likely to get metadata wrong without noticing than to get the primary key wrong.

**Comment by rfjakob** [comment]
Let's try to get some hard numbers.... Name encryption works like this:

    "foo.jpg" -> pad to 16 bytes -> AES -> base64 -> "QrAeraLdAq693QbJ1VmGgw"

Because of the padding, the resulting base64 string is always 22 characters or more. This is important, because it works in our favor. Because of the AES encryption, I'm going to assume that the resulting base64 string is a nice uniform pseudo-random value. Each base64 character encodes 6 bits of information (22 x 6 = 132), but only 128 bits are actually used.

Saving the names as all-lowercase makes it effectively base38 (because we removed the 26 uppercase letters), and each character now encodes only 5.25 bits of information, or 12.5% less than we had before. Losing 12.5% from 128 bits we remain with 112 bits of pseudo-randomness.

This is again a birthday collision problem like in https://github.com/rfjakob/gocryptfs/issues/17 , but I'm going to use the [Simple Approximation](https://en.wikipedia.org/wiki/Birthday_attack#simple_approximation) formula from Wikipedia for the collision probability:
![Screenshot from 2020-04-19 13-16-40](https://user-images.githubusercontent.com/286847/79686359-0add1400-8240-11ea-89c2-6b42151d4ba7.png)

n ... number of file names in a directory. I'm assuming 1 million files.
H ... number of possible case-insensitive names = 2^112

We get 9.6e-23 (using Wolfram Alpha):

[![Screenshot from 2020-04-19 13-58-29](https://user-images.githubusercontent.com/286847/79687214-e421dc00-8245-11ea-8adf-641403e50a52.png)](https://www.wolframalpha.com/input/?i=p+%3D+n%5E2%2F%282*H%29+where+n%3D1.0e6%2C+H%3D2%5E112.0)

Revisisting https://github.com/rfjakob/gocryptfs/issues/17#issuecomment-169020984 , NIST recommends 2.3e-10 or lower for GCM nonce collisions (which are catastrophic for security). I think we're ok with 9.6e-23 :)

**Comment by rfjakob** [comment]
Asked a mathematician and he came up with a similar number.

As for Dropbox losing all case information for file names: I have never heard of something like this happen for any cloud provider. I think they understand that users want to keep their uppercase words ;)
