### ISSUE TITLE
Some questions about the reverse mode and the treat model Dragon

### ISSUE THREAD

**Issue by kidburglar** [rfjakob/gocryptfs#494]
Hello,

I just started to use gocryptfs for storing some data in the cloud. My provider use end-to-end encryption so it would not be really useful but I still prefer to have an extra security layer if I can.

My first question is about the reverse mode. In which occasion I would need to use the reverse mode, I not really understand?

My second question is about the Dragon treat model.

- Tracking changed blocks: if I'm right it mean that it could at best guess that some "location" are more used than other?

- Modifying files and Deleting files: it could make file unusable or missing but it would be noticed by gocryptfs? Maybe not missing files?

- Renaming files: it not sound like a very big issue, I'm not sure it would be nice that gocryptfs could notice that someone tried to perform that attack but I'm not sure it's possible

- Directory IV Poisoning: I think it's in the same part of modifying there are no way to protect against it but maybe a way that gocryptfs could notice something is "wrong"?

Sorry it's not very clear but my questions are more related to if I understand the "issues" correctly and does gocryptfs offer a way that the user can notice that there is an issue. If we can notice it, it could also be a way for the user to know if a cloud provider is trying to do something fishy.

Have a good day.

**Comment by rfjakob** [comment]
Hi! I guess I'm a little late, but maybe answers are still useful to you or somebody else reading this ticket...

> In which occasion I would need to use the reverse mode?

Primary use case is encrypted backups. For example, you have a folder "data", and you want to rsync it to an external server. With reverse mode, you can create an encrypted view of "data", let's call it "data.encrypted", and rsync this to the external server. "data.encrypted" does not take any disk space, it's just an encrypted view of "data".

> Tracking changed blocks: if I'm right it mean that it could at best guess that some "location" are more used than other?

Correct!

> Modifying files and Deleting files: it could make file unusable or missing but it would be noticed by gocryptfs? Maybe not missing files?

Deleted files are not noticed by gocryptfs. An attacker could delete some random files to try to annoy you. Also they could zero-out 4 kB blocks. This would not be detected by gocryptfs.

> Renaming files: it not sound like a very big issue, I'm not sure it would be nice that gocryptfs could notice that someone tried to perform that attack but I'm not sure it's possible

Due to the encryption model that gocryptfs uses (one to one mapping of encrypted to plain files) it is not possible to detect this attack. If you store data for long-term archiving, it may make sense to also store a SHA256SUM file. This would allow you to detect renamed, deleted, modified files.

> Directory IV Poisoning: I think it's in the same part of modifying there are no way to protect against it but maybe a way that gocryptfs could notice something is "wrong"?

gocryptfs does not detect this attack. Theoretically, it could, by remembering all gocryptfs.diriv it knows and see if has duplicates. But I find the attack not very interesting so I don't think the complexity is worth it.
