### ISSUE TITLE
lack of support for macfuse (osxfuse > 3.x) 

### ISSUE THREAD

**Issue by ryangroth5** [rfjakob/gocryptfs#544]
Apple silicon macs require macfuse 4.0. Gocryptfs complains that it can't find osxfuse (3.x) if macfuse is running.

Curiously google searches don't seem to provide any tips on how to provide a compatibility layer on the macfuse side or compile against macfuse on the gocryptfs side.

**Comment by rfjakob** [comment]
Should work since https://github.com/rfjakob/gocryptfs/commit/ac2e5baa1308e5cb4ea7c0bffe01907cec8df9f2 (merged a few days ago). I added a note to the README (https://github.com/rfjakob/gocryptfs/commit/5d498f3a24ea277aff7db0f78e0153383e473dc6)

You will need to compile yourself, though: https://github.com/rfjakob/gocryptfs#compile

**Comment by rfjakob** [comment]
Please reopen if it doesn't!
