### ISSUE TITLE
Please add a donate button or crowdfunding campaign

### ISSUE THREAD

**Issue by andrewparks** [rfjakob/gocryptfs#55]
gocryptfs is looking likely to become a critical infrastructure element that millions of people will benefit from. Everyone with a NAS should be using this instead of relying on the NAS's own security. Everyone using cloud storage should be using gocryptfs.

Please add a donate button or crowdfunding campaign - the world will want to get you a MacBook to help with the OSX version, will want to provide funds for any future security audits, and will want you to be rewarded for this extremely important project.

**Comment by bgw** [comment]
You can donate to specific features through [Bountysource](https://www.bountysource.com/teams/gocryptfs). I agree it would be nice to have a monthly or ad-hoc donation system.

**Comment by rfjakob** [comment]
Thanks for the ticket and your enthusiasm! It got me thinking, and I noticed that gocryptfs does miss an invitation of taking part in the project. So, I wrote this, what do you think? https://nuetzlich.net/gocryptfs/contribute/

I'll not take direct donations because I honestly don't know how I'd use donation money transparently and effectively. I think setting bounties on features is great because it encourages developers to contribute to gocryptfs.

**Comment by bgw** [comment]
About the mailing list: I'd recommend checking out [librelist](http://librelist.com/).

About money: I'd be interested in helping to fund a security audit. Would bountysource be a good mechanism for this?

**Comment by rfjakob** [comment]
Yes, librelist, I stumbled over it once but could not figure out if it's alive or dead. Do you know any details? Lots of 2009 timestamps over there.

Ad security audit: Creating a tracking ticket and collecting through bountysource sounds like it could work, yes.

Another thing I was thinking about is adding user testimonials to the website. On one hand I'm genuinely interested how people use gocryptfs, on the other hand writing a testimonial is a super-low-entry-barrier-way of contributing. The first testimonial would have to be something like this, of course, because humor is always important:

> I stored all of my data in gocryptfs. Then I forgot my password and I also did not
> have a copy of my master key. I never got my data back. Just as advertised,
> awesome product!

**Comment by andrewparks** [comment]
Here's why I think it'd be a huge mistake to rely on BountySource:

There are two types of donors. There are home users like me that have a NAS and can contribute modest amounts out of good will.

But then several people that come across your product work for companies. They expense $2000 business trips all the time and spend 6 figure sums on their internal NAS and cloud storage infrastructure. People like this, that come across your project, will be able to put a minimum of $300 on their company credit card with almost no approval required, just like they could expense a piece of software or a business lunch with a client. The last thing you want to do with people like that is ask them to do any work or fill in any requests. You should just let them send money because they think you are working on something that will be useful to them in under a year's time.

Completing a security audit is not only a great way to convince people to adopt gocryptfs, but it would be a great 'news item' to get the word out. Having a crowdfund for this will give people confidence that you're actively working towards that goal, and that they're not just sending money blindly into the ether.

One other thing: I know it's probably not your personality type, but here is something I vey strongly recommend:

Spend just a few hours emailing relevant people at a bunch of cloud providers asking for donations. They know that having their logo on your site as sponsors will generate good will for them and demonstrate to their customers that they are forward looking technically savvy operators and not just mindless marketing people that don't put much thought into their technical infrastructure. I'm sure you could easily generate $5000 with just a few hours of emails. If you've never done this before, you probably don't realise how incredibly easy it is. As a student, I cold contacted dozens of companies and they sent $300 each to help pay for various events without even thinking. It vaguely met a goal to generate good will for their company, and it was a small amount, so they didn't think twice. This will work for you, I promise.

Good luck, I genuinely believe you are working on what will become a massively widely used and much loved piece of critical infrastructure.

**Comment by rfjakob** [comment]
Andrew, thanks again for the ideas and the encouragement, but I still think that's not something I will do, so I'm gonna close the ticket.

**Comment by balupton** [comment]
+1 for github sponsors, I try to sponsor everything I depend on as a thank you for prior work, so no issue with whatever you spend it on, as you already earned it
