### ISSUE TITLE
Data lost when root file system is full

### ISSUE THREAD

**Issue by lechner** [rfjakob/gocryptfs#550]
Hi,

Someone filed a [release-critical bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=984716) in Debian, with `bullseye` only weeks away. Would you please take a look?

Here are some friendly observations from third parties:
```
so improper error handling. the strace output shows sqlite, so maybe it breaks if data and metadata diverge
```
and
```
wasn't that one of btrfs's failure modes?
```
Thanks for looking into it!

Kind regards
Felix Lechner

**Comment by rfjakob** [comment]
Hi, I read through the bug report, some points about gocryptfs's design first:

1) There is no database.
2) gocryptfs does not read nor write outside outside of the encrypted directory.
3) If encrypted directory goes out of space, gocryptfs will return ENOSPC to write requests, but nothing will break. Even the last block written will not be corrupt (truncated) because gocryptfs preallocates the space beforehand (using `FALLOC_FL_KEEP_SIZE`).

In the bug report, we see errors about some `._sync_xxxxxx.db-xyz` files. These [seem to belong to nextcloud](https://github.com/nextcloud/desktop/issues/1702). gocryptfs warns because it cannot decrypt them, but will otherwise ignore them.

The real corruption is this:
```
fsck: error opening dir "(...)": 2=no such file or directory
```
This means the `gocryptfs.diriv` file is missing. On gocryptfs v2.0, fsck gives some more detail:
```
OpenDir "vL8EKwBafpLJK1dmVSUMtg": could not read gocryptfs.diriv: no such file or directory
fsck: error reading dir "x": readdirent: input/output error
```

In any case, I don't understand how the `gocryptfs.diriv` files could possibly disappear

**Comment by MatthiasJaeger** [comment]
Hi, this is the original Debian bug report submitter. I have since, in the process of recovery, collected a few more details.

You are correct about the db files. They are from nextcloud. It is possible that the underlying problem was caused by nextcloud. I didn't assume that as the online sync of the data stayed unchanged.

In the encrypted directory from the original bug report multiple folders lost their content. All of those folders were direct subfolders of the main directory. Their encrypted version is missing all data. Both the files and the gocryptfs.diriv file as well as all encrypted files and directories. All of the newly empty directories show the same change date.

The file system that contains the encrypted directory was not full at any time. Only the root filesystem was. The Operating system was in a strange state as after deleting multiple log files with > 1 GB each the root file system still reported to be full and I had to do a reboot to fix that.

Since the bug report I fund missing data in a second gocryptfs encrypted directory. Again it is one that is synced (separately) with Nextcloud. It is on a different ext4 partition that also wasn't full. Again the content of multiple directories is missing. All directories with missing data are direct subdirectories of a common directory but in this case the common directory isn't the the main encrypted directory but a subdirectory thereof. Again all the directories that are missing their content have the same change date but a few minutes before the change date of the missing directories in the other case.

Both file systems were mounted using the `-sharedstorage` option.

I didn't have any files opened that were in the directories now missing. I also didn't find any other directories outside gocryptfs/nextcloud that are missing. There is one potential candidate: a subdirectory of the home directory containing part of the Skype configuration showed a similar changedate and I has to login to Skype after the restart. But that could be completely unrelated given the strangeness of that closed source app. If it were related it would be a much higher level operating system problem as that folder is just a normal folder on a normal not overfilled and not cloud-synced ext4 drive.

If you are sure, that nothing in gocryptfs can cause this (even with the os behaving strangely) the next most likely cause would probably be nextcloud.

**Comment by rfjakob** [comment]
Thanks for the detailed write-up!

> after deleting multiple log files with > 1 GB each the root file system still reported to be full and I had to do a reboot to fix that.

My guess is that you deleted less than what was reserved for root, and/or the files were still open, which means the space is not freed until the files are closed. Rebooting does the trick :)

As for the missing files: gocryptfs never deletes stuff on it's own, it actually does not do anything by itself. There is no background processing going on or anything like that.

And when it does delete a directory, at the request of the user via a FUSE request, gocryptfs is very careful to not leave a directory without gocryptfs.diriv behind.

It seems unlikely to me that gocryptfs somehow did this.
