### ISSUE TITLE
Feature Request: File size obfuscation

### ISSUE THREAD

**Issue by fabiopesaju** [rfjakob/gocryptfs#57]
sorry if someone already asked...

I saw the comparison page (https://nuetzlich.net/gocryptfs/comparison/)

  and I would like to know if you intend to implement the functionality to obfuscate the file size. and also the functionality obfuscate the directory structure...

I know this can impact on be some problems, but this option could be available to anyone who would enable it...

**Comment by rfjakob** [comment]
No, you are the first one ;)

Unfortunately, file size obfuscation is somewhat incompatible with what gocryptfs wants to be: fast, simple design, POSIX-correct. Essentially what EncFS is but with modern cryptography (GCM and EME).

So no, this is not planned. Cryptomator used to have file size obfuscation but dropped it in v1.2.0 because of speed concerns (check their [release announcement](https://github.com/cryptomator/cryptomator/releases/tag/1.2.0) for details).

I guess you already have seen it if you read the comparison, but check out [CryFS](https://www.cryfs.org/), which has been designed with file size and directoy obfuscation at it's core.

**Comment by fabiopesaju** [comment]
I met cryfs here on our company, but I saw the cited problem with speed. and also problems with the size of the blocks, cryfs does not allow setting dynamic blocks. ( https://github.com/cryfs/cryfs/issues/70 )

I have not done tests with gocryptfs, but seeing your comparison table and observing the speed, I thought that gocryptfs might perform better in this situation to obfuscate the file size and the structure of directories.

**Comment by rfjakob** [comment]
cryfs#70 was an interesting read, thanks. Maybe some of the performance issues in CryFS can be fixed, for example I did not understand why it has to read the complete block when it reads a directory ( https://github.com/cryfs/cryfs/issues/68#issuecomment-229502630 ).

But one of the reasons that gocryptfs is fast is because it just does not do a lot of the things that CryFS does. Adding file size obfuscation would also be a big performance hit for gocryptfs.

**Comment by fabiopesaju** [comment]
but it could be offered as an optional feature... to use, you will know what will be compromised, no?

**Comment by rfjakob** [comment]
Yes, but why should gocryptfs duplicate the work that CryFS has already
done?

**Comment by VitCN** [comment]
Interested as well. CryFS' rather extreme fixed size files approach to completely hide file sizes has big drawbacks in speed and scalability so gocryptfs with some file size obfuscation would be a much better choice for when obfuscation is sufficient.

**Comment by rfjakob** [comment]
Ok, let's keep this open, maybe I (or somebody else - contributions welcome!) has an idea for how to implement this efficiently.

**Comment by vampywiz17** [comment]
Well my idea is (first off, I'm not a programmer so i only just add a idea and you guys will say that is possible the implement it to the code):

CryFS do a block sized Obfuscation, but it is decrease the speed and generate problems cloud mounts (block size problem)

My idea: add all off encrypted file a random generated null bits (for example about 1-50 Mb size, depending on the original file size) this difference is stored all ecrypted files and the decryption process the system automaticaly shrink the "unnecessary" bits on end of file.

It not generate (i think) a lot of performance claim, but the encrypted file size a bit different the original size.

Cons: it increase a bit the encrypted file size and the upload process a bit longer.

**Comment by pepa65** [comment]
As long as this feature is optional... I think you should not go with file encryption if you want the file sizes to be obfuscated, just put them all in a single encrypted block device.

**Comment by rfjakob** [comment]
@vampywiz17 No that idea is fine, actually it is what ecryptfs is doing :) Unfortunately this is also why ecryptfs is pretty slow, because it has to read the file header just to find out the real file size.

It's been a few months now and I still don't see how this could be implemented without hitting the problems CryFS and cryptomator have hit. I think if you want high performance with file size obfuscation you should go with an encrypted loop-mounted file. I'll close this as WONTFIX.

**Comment by franciscoluiz** [comment]
Hello... I wrote this https://github.com/cryfs/cryfs/issues/70 ...

I understand your concern regarding performance VS hide file size...

But think about it, if it's exactly like cryfs, you'll actually have the same problem. But if you read the examples I mentioned in the course of that issue (https://github.com/cryfs/cryfs/issues/70#issuecomment-231387226), and generate the file size dynamically, I do not think there will be a sudden loss of performance...

**Comment by script26** [comment]
I don't know if this helps or not, but I was also really curious about hiding not just file size, but directory structure, and realized it is possible to do so with gocryptfs, but just making an empty container (not encrypted). It is just linux stuff:

mkdir ./gocryptfs ./gocryptfs_mnt ./container_mnt
gocryptfs -init gocryptfs
gocryptfs ./gocryptfs ./gocryptfs_mnt

dd if=/dev/zero of=crypt_container bs=1M count=1000 #1GB File
mkfs.ext4 ./crypt_container
mv ./crypt_container ./gocryptfs_mnt
fuse-ext2 ./gocryptfs_mnt/crypt_container ./container_mnt -o rw+

then just ```fusermount -u ./container_mnt && fusermount -u ./gocryptfs_mnt``` when done

I tested under crostini and put a file in it and it works, this doesn't need loop module as well it seems crostini doesn't have loop module at all. Please let me know if I did anything wrong, or if this is valid or something.
