### ISSUE TITLE
Consider having git styled subcommands

### ISSUE THREAD

**Issue by impredicative** [rfjakob/gocryptfs#635]
Consider organizing the command-line interface into a set of subcommands. The [man page](https://github.com/rfjakob/gocryptfs/blob/master/Documentation/MANPAGE.md) is already separated with such organization in mind. Some applicable subcommands are `init`, `mount`, `xray`, etc. This ought to prove its utility over time. It could be a major breaking change. This is a low-priority request, but the longer the application goes without it, the more confusing the interface could get.

**Comment by rfjakob** [comment]
Yep, looking at the number of flags that gocryptfs has accumulated, using subcommands looks like a good idea.

The problem is that mounts from /etc/fstab execute like this:

    gocryptfs SRC DST -o OPTIONS

So the mount command would need the be the implicit default subcommand, and I'm not sure if that's feasible.

The second thing, and you have already mentioned it, is that this would break cli compatibility. I think it's too late for that, as in, it would cause more pain than it would improve the situation.

**Comment by rfjakob** [comment]
Looking at the example fstab line athttps://github.com/rfjakob/gocryptfs/blob/master/Documentation/MANPAGE.md#fstab , I don't see how you would put "gocryptfs mount" in there. What you can do in fstab is pretty restricted.

Breaking things for the greater good is possible, and I did already, but that was for security improvements.
