### ISSUE TITLE
The vault opens with any value in -masterkey

### ISSUE THREAD

**Issue by Helltar** [rfjakob/gocryptfs#699]
I don't understand what's going on, I create a new vault, for example password **_8293uhdcssno2HIIBH22_**, and it successfully mounts with the command:

`gocryptfs -masterkey 0000000000000000000000000000000000000000000000000000000000000000 testvault/ mntdir/`

Screencast: https://youtu.be/Jkf6Xk-KkSU

Arch Linux, [gocryptfs 2.3](https://archlinux.org/packages/community/x86_64/gocryptfs/)

**Comment by lechner** [comment]
Hi,

I believe that when you mounted the drive the first time around with `-masterkey`, Gocryptfs ignored the secrets in `gocryptfs.conf`. That's why you needed no password when mounting.

Instead, the program used the key you provided (and which contained all zeros) together with data in `gocryptfs.diriv` to encrypt the name of `001.txt`.

The file had no contents.

When you mounted the folder the second time around, you again provided the same `-masterkey`. That circumvented for a secont time the secret in `gocryptfs.conf`—which by that time had become useless because it could no longer decrypt the information you sought to protect.

You used the same key during the encryption as you did during the decryption. As a result, the filename was decrypted correctly.

Kind regards,
Felix Lechner

**Comment by Helltar** [comment]
@lechner yes, I did some more tests and seem to understand, thank you for the detailed explanation.
