### ISSUE TITLE
decrypt just one file without having to download the entire folder?

### ISSUE THREAD

**Issue by dakkusingh** [rfjakob/gocryptfs#7]
Is it possible to decrypt just one file without having to download the entire folder? This is possible with ENCFS if you disable external IV chain. This is a very useful feature if you just want to download individual files / folders from the cloud and decrypt them.

> Yes. Every file is independent.

see discussion here https://github.com/rfjakob/gocryptfs/issues/2#issue-114509562 and here https://github.com/rfjakob/gocryptfs/issues/2#issuecomment-152951598

**Comment by dakkusingh** [comment]
marking as resolved.

**Comment by lechner** [comment]
Hi, where does it explain how to decrypt a single file, please? Thank you!

**Comment by ccchan234** [comment]
so easy!? thanks (ps i use cppcryptfs, let me try)

**Comment by sillyh4ck3r** [comment]
> [@lechner](https://github.com/lechner) You can place gocryptfs.conf, your file, and the file's gocryptfs.diriv in a new empty directory. Then you can mount that and get the decrypted file.

Clarified: Put your encrypted file and your gocryptfs.conf into a new directory.  "gocryptfs.diriv" must have been a mistake.

**Comment by rfjakob** [comment]
No you also need gocryptfs.diriv, otherwise the file name cannot be decrypted.

Or you can use https://github.com/slackner/gocryptfs-inspect .

**Comment by ccchan234** [comment]
> No you also need gocryptfs.diriv, otherwise the file name cannot be decrypted.
> 
> Or you can use https://github.com/slackner/gocryptfs-inspect .

sort of off topic,
i use win10+ google drive desktop (i.e. streaming) + cppcryptfs.
sometimes the sync in stream sucks and GDRv kept a list of files that cant upload.

previously i used LLMs (mostly claude that time) to write a GUI for cppcryptfsctl.exe to "translate" filename/path between the encrypted/unencrypted folders (my GUI only provide GUI funciton, the translate is done by cppcryptfsctl.exe from cppcryptfs's author).

i found this helps very much/cant do it without the GUI.

since i only posted in cppcryptfs's github,
i just also reference it here.

and since cppcryptfs is for windows and the GUI is written in autohotkey which is also windows,
indeep this is quite far away from gocryptfs.

but, just FYI. thanks

https://github.com/bailey27/cppcryptfs/issues/200
