### ISSUE TITLE
RFE: add fido2-with-client-pin

### ISSUE THREAD

**Issue by schaarsc** [rfjakob/gocryptfs#702]
in https://github.com/rfjakob/gocryptfs/issues/571 user verification was removed. as a result currently only user presence is configured. I did not find an option to enable client pin.

I'd like to suggest to add options similar to systemd-cryptenroll
- fido2-device
- fido2-with-client-pin=BOOL, defaul=yes
- fido2-with-user-presence=BOOL, default=yes
- fido2-with-user-verification=BOOL, default=no

the selected options should be added to gocryptfs.conf

Possible solution
depending on the selected option, add `-t [up|uv|pin] `to line https://github.com/rfjakob/gocryptfs/blob/69d88505fd7f4cb0d9e4f1918de296342fe05858/internal/fido2/fido2.go#L44

**Comment by aanno** [comment]
Hm, with `gocryptfs v2.3.2-12-gc674544 without_openssl`, I was not able to use a legacy (very old) FIDO2 hardware token (apparently because it does not support a PIN). With [solokey somu](https://github.com/solokeys/solo1), I had to enter my PIN for `init`. Hence I wonder if this is still relevant?!?

**Comment by schaarsc** [comment]
I think it is required to get a consistent behavior across tokens/vendors.
it is also required for user verification, which is not supported by all tokens.

**Comment by viric** [comment]
I came to this ticket because I also wanted PIN asked for gocryptfs mount. I'm using Nitrokey FIDO2 and the PIN is not asked in gocryptfs 2.3.2.
